version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: citycycle-app
    container_name: citycycle-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - citycycle-network

  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: citycycle
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - citycycle-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - citycycle-network

volumes:
  mysql-data:
    driver: local

networks:
  citycycle-network:
    driver: bridge
